[versions]
agp = "8.2.2"
android-minSdk = "24"
android-targetSdk = "34"
kotlin = "2.0.0"
compose = "1.6.1"
compose-compiler = "1.5.14"
navigation = "2.7.7"
realm = "1.13.0"
koin = "3.5.3"
vico = "1.13.1"
coroutines = "1.7.3"
kotest = "5.8.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.8.2" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.7.0" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version = "1.6.1" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version = "1.6.1" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.6.1" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.1" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "1.6.1" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.6.1" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.6.1" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
realm-base = { module = "io.realm.kotlin:library-base", version.ref = "realm" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
vico-compose = { module = "com.patrykandpatrick.vico:compose", version.ref = "vico" }
vico-compose-m3 = { module = "com.patrykandpatrick.vico:compose-m3", version.ref = "vico" }
vico-core = { module = "com.patrykandpatrick.vico:core", version.ref = "vico" }
kotest-framework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
